debug: True

params:
  # List all the likelihood parameters here.
  # You need to include `prior`, `ref` and
  # `proposal` for all parameters you want
  # to vary.
  clk_log10meff:
    prior:
      min: 11.5
      max: 14
    ref:
      dist: norm
      loc: 12.14
      scale: 0.01
    latex: log_{10}(M_{peak})
    proposal: 0.001
  clk_etamax:
    prior:
      min: 0.
      max: 1.
    ref:
      dist: norm
      loc: 0.41
      scale: 0.01
    latex: \eta_{max}
    proposal: 0.001
  clk_sigLM0:
    prior:
      min: 0.
      max: 4.
    ref:
      dist: norm
      loc: 2.11
      scale: 0.01
    latex: \sigma_{M,0}
    proposal: 0.001
  clk_tau:
    prior:
      min: 0.
      max: 3.
    ref:
      dist: norm
      loc: 1.05
      scale: 0.01
    latex: \tau
    proposal: 0.001
  sigma8: 0.8102
  Omega_c: 0.26066676
  Omega_b: 0.048974682
  h: 0.6766
  n_s: 0.9665
  m_nu: 0.

theory:
  cl_like.CCL:
    matter_pk: halofit
    baryons_pk: nobaryons

likelihood:
  cl_like.ClLike:
    # Input sacc file
    input_file: cls_cov_all_shearcross.fits
    # List all relevant bins. The clustering
    # bins are clX, the shear bins are shX.
    bins:
      - name: KiDS1000__4
      - name: CIBLenz__0
    # List all 2-points that should go into the
    # data vector. For now we only include
    # galaxy-galaxy auto-correlations, but all
    # galaxy-shear and shear-shear correlations.
    twopoints:
      - bins: [KiDS1000__4, CIBLenz__0]

    defaults:
      # Scale cut for galaxy clustering
      # (ignored for shear-shear)
      kmax: 0.15
      # These one will apply to all power
      # spectra (unless the lmax corresponding
      # to the chosen kmax is smaller).
      lmin: 0
      lmax: 2000
      KiDS1000__4:
        lmin: 100
      CIBLenz__0:
        lmin: 100

    # Prefix associated to all nuisance params
    input_params_prefix: clk
    ia_model: IANone
    nz_model: NzNone
    shape_model: ShapeNone
    bias_model: HaloModel

    # Halo model parameters
    mf_name: Tinker08
    hb_name: Tinker10
    cm_name: Duffy08
    mass_def_str: 200c
    HM_correction: halofit
    

output: "tests/"
